/**
 * Fetches primary product image URLs from Amazon Product Advertising API 5.0 (GetItems).
 * Requires PA-API credentials from your Amazon Associates account (not the same as login password).
 * See: https://webservices.amazon.com/paapi5/documentation/register-for-pa-api.html
 *
 * Usage: AMAZON_PA_API_ACCESS_KEY=... AMAZON_PA_API_SECRET_KEY=... npm run fetch-images
 */

import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { affiliateLinks, ACTIVE_PROGRAMS } from '../src/data/affiliates';

const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ProductAdvertisingAPIv1 = require('paapi5-nodejs-sdk') as any;

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '../src/data/amazon-images.generated.ts');

function extractAsin(url: string): string | null {
  const m = url.match(/\/dp\/([A-Z0-9]{10})/i);
  return m ? m[1].toUpperCase() : null;
}

function escapeTs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

async function main() {
  const accessKey = process.env.AMAZON_PA_API_ACCESS_KEY;
  const secretKey = process.env.AMAZON_PA_API_SECRET_KEY;
  const partnerTag = process.env.AMAZON_ASSOCIATE_TAG || ACTIVE_PROGRAMS.amazon.tag;

  const pairs: { id: string; asin: string }[] = [];
  for (const a of affiliateLinks) {
    if (a.available === false) continue;
    const asin = extractAsin(a.url);
    if (asin) pairs.push({ id: a.id, asin });
  }

  if (!accessKey || !secretKey) {
    console.log(
      'Missing AMAZON_PA_API_ACCESS_KEY or AMAZON_PA_API_SECRET_KEY.\n' +
        'Get keys from Amazon Associates → Product Advertising API.\n' +
        'Writing empty amazon-images.generated.ts (manual images in affiliates.ts still work).\n',
    );
    writeFileSync(
      OUT,
      '/** Populated by npm run fetch-images when PA-API env vars are set. Safe to commit empty. */\n' +
        'export const amazonGeneratedImages: Partial<Record<string, string[]>> = {};\n',
    );
    process.exit(0);
  }

  const defaultClient = ProductAdvertisingAPIv1.ApiClient.instance;
  defaultClient.accessKey = accessKey;
  defaultClient.secretKey = secretKey;
  defaultClient.host = 'webservices.amazon.com';
  defaultClient.region = 'us-east-1';

  const api = new ProductAdvertisingAPIv1.DefaultApi();
  const asinToIds = new Map<string, string[]>();
  for (const { id, asin } of pairs) {
    const list = asinToIds.get(asin) ?? [];
    list.push(id);
    asinToIds.set(asin, list);
  }
  const uniqueAsins = [...asinToIds.keys()];

  const idToUrls: Record<string, string[]> = {};

  const chunk = <T,>(arr: T[], size: number): T[][] => {
    const out: T[][] = [];
    for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
    return out;
  };

  for (const batch of chunk(uniqueAsins, 10)) {
    const getItemsRequest = new ProductAdvertisingAPIv1.GetItemsRequest();
    getItemsRequest.PartnerTag = partnerTag;
    getItemsRequest.PartnerType = 'Associates';
    getItemsRequest.ItemIds = batch;
    getItemsRequest.Resources = ['Images.Primary.Large'];

    const data: unknown = await new Promise((resolve, reject) => {
      api.getItems(getItemsRequest, (err: Error | null, d: unknown) => {
        if (err) reject(err);
        else resolve(d);
      });
    });

    const response = ProductAdvertisingAPIv1.GetItemsResponse.constructFromObject(data);
    const items = response.ItemsResult?.Items ?? [];
    for (const item of items) {
      const asin = item.ASIN as string;
      const url = item.Images?.Primary?.Large?.URL as string | undefined;
      if (!url) continue;
      const ids = asinToIds.get(asin) ?? [];
      for (const id of ids) {
        idToUrls[id] = [url];
      }
    }
  }

  const lines = Object.entries(idToUrls)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, urls]) => `  '${escapeTs(id)}': [${urls.map((u) => `'${escapeTs(u)}'`).join(', ')}],`)
    .join('\n');

  const file =
    `/** AUTO-GENERATED by scripts/fetch-amazon-images.ts — do not edit by hand */\n` +
    `export const amazonGeneratedImages: Partial<Record<string, string[]>> = {\n${lines}\n};\n`;

  writeFileSync(OUT, file);
  console.log(`Wrote ${Object.keys(idToUrls).length} product image URL(s) to src/data/amazon-images.generated.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
